-- Seed initial categories
INSERT INTO categories (name) VALUES
('Electrician'),
('Plumber'),
('AC Technician'),
('Generator Repair'),
('Handyman'),
('Masonry'),
('Welder'),
('Yard Cleanup / Landscaping'),
('Septic Services'),
('Roofing'),
('Pest Control'),
('Appliance Repair'),
('Carpenter'),
('Painter'),
('Locksmith'),
('Cleaning Service'),
('Music'),
('Technology'),
('Fitness');