ALTER TYPE activity_event_type ADD VALUE IF NOT EXISTS 'CUSTOMER_CALL';
ALTER TYPE activity_event_type ADD VALUE IF NOT EXISTS 'CUSTOMER_SMS';
ALTER TYPE activity_event_type ADD VALUE IF NOT EXISTS 'CUSTOMER_EMAIL';
ALTER TYPE activity_event_type ADD VALUE IF NOT EXISTS 'CUSTOMER_VIEW';
ALTER TYPE activity_event_type ADD VALUE IF NOT EXISTS 'CUSTOMER_CLICK';
